### PR TITLE
Feature/expo

### PR DESCRIPTION
**Pull request by shyambhongle**
We are transitioning from React Native to Expo architecture with this PR. It includes all the changes related to TreeMapper 2.0, which encompasses the Intervention, Monitoring Plot, and Re:measurement features.  

Additionally, it supports the latest SDK versions for Android and iOS. We’ve also updated to Expo SDK version 51, which incorporates React Native 74+. Once this PR is merged, all new features, implementations, and fixes will be applied to this branch.

### CODE REVIEW

**Comment by norbertschuler** [comment]
> Hi Norbert, I discovered that the build was failing during a clean Android build (performing yarn install) due to the version of MapLibre we are using which has issue with expo SDK 51. I have added a patch in this [branch](https://github.com/Plant-for-the-Planet-org/treemapper/tree/feature/maplibre-android-patch). Should I merge it now, or wait until it is merged into develop?

Have you also tried an iOS build? I did a clean setup and got a native crash from the iOS simulator of Xcode like this (shortened the error report):
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 0DB874DB-BDFC-4754-A663-C2E1DA2BB733
CrashReporter Key:   69ED6FA5-BC36-5782-AC73-F5F3064C07EB
Hardware Model:      MacBookPro18,3
Process:             TreeMapper [55215]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/03F50164-099B-40F1-B352-38EA339939D2/data/Containers/Bundle/Application/A35569BB-71CF-4519-AF61-AF01DC46CC36/TreeMapper.app/TreeMapper
Identifier:          org.pftp.treemapper
Version:             2.0.3 (1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [54167]
Coalition:           com.apple.CoreSimulator.SimDevice.03F50164-099B-40F1-B352-38EA339939D2 [16538]
Responsible Process: SimulatorTrampoline [2612]

Date/Time:           2024-07-31 12:12:58.5098 +0700
Launch Time:         2024-07-31 12:12:47.4225 +0700
OS Version:          macOS 14.6 (23G80)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x0000000177fbc000
Exception Codes: 0x0000000000000002, 0x0000000177fbc000
VM Region Info: 0x177fbc000 is in 0x177fbc000-0x177fcc000;  bytes after start: 0  bytes before end: 65535
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      OpenGL GLSL                 177fb4000-177fbc000    [   32K] rw-/rwx SM=ZER  
--->  VM_ALLOCATE                 177fbc000-177fcc000    [   64K] rwx/rwx SM=PRV  
      GAP OF 0x34000 BYTES
      MALLOC_SMALL                178000000-178800000    [ 8192K] rw-/rwx SM=PRV  
Termination Reason: SIGNAL 10 Bus error: 10
Terminating Process: exc handler [55215]

Triggered by Thread:  6

Thread 0::  Dispatch queue: com.apple.main-thread
0   libGLProgrammability.dylib    	       0x1a63e8d84 glvmGetSourceOffsetStride + 1292
1   libGLProgrammability.dylib    	       0x1a6409588 glvmInterpretFPTransformFourInner + 956
2   libGLProgrammability.dylib    	       0x1a640c198 glvmInterpretFPTransformFour + 2536
3   GLRendererFloat               	       0x1cabb9430 gldLLVMFPTransform + 484
4   GLRendererFloat               	       0x1cabc87ec gldLLVMVecPolyRender + 19348
5   GLRendererFloat               	       0x1cabb6338 gldRenderFillPolygonPtr + 92
6   GLEngine                      	       0x1a638c1e4 gleLLVMVecPrimMultiRender + 6204
7   GLEngine                      	       0x1a632bf64 gleDrawArraysOrElements_ExecCore + 1012
8   GLEngine                      	       0x1a632afd0 glDrawElements_ES2Exec + 396
9   Mapbox                        	       0x109459a68 mbgl::gl::Context::draw(mbgl::gfx::DrawMode const&, unsigned long, unsigned long) + 136
10  Mapbox                        	       0x10949909c mbgl::gl::Program<mbgl::ClippingMaskProgram>::draw(mbgl::gfx::Context&, mbgl::gfx::RenderPass&, mbgl::gfx::DrawMode const&, mbgl::gfx::DepthMode const&, mbgl::gfx::StencilMode const&, mbgl::gfx::ColorMode const&, mbgl::gfx::CullFaceMode const&, mbgl::gfx::UniformValues<mbgl::TypeList<mbgl::uniforms::matrix>> const&, mbgl::gfx::DrawScope&, mbgl::gfx::AttributeBindings<mbgl::TypeList<mbgl::attributes::pos>> const&, mbgl::gfx::TextureBindings<mbgl::TypeList<>> const&, mbgl::gfx::IndexBuffer const&, unsigned long, unsigned long) + 768
11  Mapbox                        	       0x109516960 void mbgl::Program<mbgl::ClippingMaskProgram, (mbgl::gfx::PrimitiveType)2, mbgl::TypeList<mbgl::attributes::pos>, mbgl::TypeList<mbgl::uniforms::matrix>, mbgl::TypeList<>, mbgl::style::Properties<>>::draw<mbgl::gfx::Triangles>(mbgl::gfx::Context&, mbgl::gfx::RenderPass&, mbgl::gfx::Triangles const&, mbgl::gfx::DepthMode const&, mbgl::gfx::StencilMode const&, mbgl::gfx::ColorMode const&, mbgl::gfx::CullFaceMode const&, mbgl::gfx::IndexBuffer const&, std::__1::vector<mbgl::Segment<mbgl::TypeList<mbgl::attributes::pos>>, std::__1::allocator<mbgl::Segment<mbgl::TypeList<mbgl::attributes::pos>>>> const&, mbgl::gfx::UniformValues<mbgl::TypeList<mbgl::uniforms::matrix>> const&, mbgl::gfx::AttributeBindings<mbgl::TypeList<mbgl::attributes::pos>> const&, mbgl::gfx::TextureBindings<mbgl::TypeList<>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 192
12  Mapbox                        	       0x1095167e8 mbgl::PaintParameters::renderTileClippingMasks(std::__1::shared_ptr<std::__1::vector<std::__1::reference_wrapper<mbgl::RenderTile const>, std::__1::allocator<std::__1::reference_wrapper<mbgl::RenderTile const>>> const> const&) + 828
13  Mapbox                        	       0x1094ea968 mbgl::RenderFillLayer::render(mbgl::PaintParameters&) + 104
14  Mapbox                        	       0x10952d548 mbgl::Renderer::Impl::render(mbgl::RenderTree const&) + 1468
15  Mapbox                        	       0x10952bf38 mbgl::Renderer::render(std::__1::shared_ptr<mbgl::UpdateParameters> const&) + 64
16  Mapbox                        	       0x1097701d4 MGLRenderFrontend::render() + 68 (MGLRendererFrontend.h:57) [inlined]
17  Mapbox                        	       0x1097701d4 -[MGLMapView renderSync] + 212 (MGLMapView.mm:1025)
18  Mapbox                        	       0x109731500 MGLMapViewImpl::render() + 16 (MGLMapView+Impl.mm:14) [inlined]
19  Mapbox                        	       0x109731500 -[MGLMapViewImplDelegate glkView:drawInRect:] + 32 (MGLMapView+OpenGL.mm:26)
20  GLKit                         	       0x1b8a9858c -[GLKView _display:] + 184
21  QuartzCore                    	       0x18a1b2e34 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 392
22  QuartzCore                    	       0x18a0ebf54 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 460
23  QuartzCore                    	       0x18a11bcd0 CA::Transaction::commit() + 652
24  QuartzCore                    	       0x18a020030 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 1300
25  QuartzCore                    	       0x18a120c98 display_timer_callback(__CFMachPort*, void*, long, void*) + 336
26  CoreFoundation                	       0x1803d8a20 __CFMachPortPerform + 172
27  CoreFoundation                	       0x18040f588 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
28  CoreFoundation                	       0x18040eb58 __CFRunLoopDoSource1 + 496
29  CoreFoundation                	       0x180409168 __CFRunLoopRun + 2176
30  CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
31  GraphicsServices              	       0x18ef2aae4 GSEventRunModal + 160
32  UIKitCore                     	       0x1853d0a28 -[UIApplication _run] + 868
33  UIKitCore                     	       0x1853d46b0 UIApplicationMain + 124
34  TreeMapper                    	       0x10217c800 main + 96 (main.m:7)
35  dyld_sim                      	       0x106b65544 start_sim + 20
36  dyld                          	       0x106c3a154 start + 2476
...
```

**Comment by norbertschuler** [comment]
> Hi Norbert, I discovered that the build was failing during a clean Android build (performing yarn install) due to the version of MapLibre we are using which has issue with expo SDK 51. I have added a patch in this [branch](https://github.com/Plant-for-the-Planet-org/treemapper/tree/feature/maplibre-android-patch). Should I merge it now, or wait until it is merged into develop?

This branch also works for me (tested on Android emulator for API level 30). So I think you should merge your patch.

**Comment by shyambhongle** [comment]
Hi @norbertschuler ,
I’ve updated the PR with the latest changes.

**Review by norbertschuler — APPROVED** [review]
I tested running on my iPhone 13 and on an Android emulator works. I have not tested all the available functionality.

**Comment by shyambhongle** [comment]
Hi @sagararyal ,
This PR is ready to be merged into both the develop and main branches. It will override all previous code. Can we proceed with building the production APK and iOS archive.
Norbert has already prepared the App Store listing for version 2.0.0, and I will be adding the metadata for it.

**Pull request merged**
