### PR TITLE
Feature/bug fixes

### LINKED ISSUE #347: UI bugs
- Padding on Sync component, replace the hyphen with centre dot
- Title should be "Review of Tree 1 of 5", on Sample Tree Review
- clicking outside ProfileModal should close it
- Icon to close the TreeCount Modal.

**Screenshots**
image
image
image
image

### PR DESCRIPTION
**Pull request by tejassonar**
Fixes #347 #349  #339 

Changes in this pull request:
- Changed statuses of inventory to show uploading inventory
- Changed notification bar colour
- Solved issue repetitively fetching all inventories from the database

### CODE REVIEW

**Review by norbertschuler — COMMENTED** [review]
Verified https://github.com/Plant-for-the-Planet-org/treemapper/issues/339 is working. I cannot say if the UI issues are fixed.

**Comment by tejassonar** [comment]
> Verified #339 is working. I cannot say if the UI issues are fixed.

Can you tell me, which issues exactly are not fixed?

**Comment by norbertschuler** [comment]
> > Verified #339 is working. I cannot say if the UI issues are fixed.
> 
> Can you tell me, which issues exactly are not fixed?

Sorry. It just meant I had not tested UI fixes yet.

**Comment by norbertschuler** [comment]
- [ ] Minimum value is 5, so this dialog shows up if the user enters 0,1,2,3 or 4 - we should adapt the dialog text to show the minimum value to avoid irritations for the user:

Simulator Screen Shot - iPhone 11 - 2021-06-04 at 11 06 07

**Comment by norbertschuler** [comment]
> 



> * [x]  Minimum value is 5, so this dialog shows up if the user enters 0,1,2,3 or 4 - we should adapt the dialog text to show the minimum value to avoid irritations for the user:

The English resource already got adapted, sorry!

**Review by norbertschuler — APPROVED** [review]
Tried to check all UI fixes. Looks ok for me.

**Pull request merged**
