### PR TITLE
Missing data fix

### PR DESCRIPTION
**Pull request by ankitecd**
This PR check for all the existing registrations and mark them as FIX_NEEDED if any missing data is found. Then ask the user to fix the missing data in registration from the Tree Inventory page.

To test this PR go to this [comment](https://github.com/Plant-for-the-Planet-org/treemapper/pull/553#issuecomment-1009688143)

Fixes bug where some sample trees or single trees where shown as species. diameter or height is not able to be identified 

Image from iOS

### CODE REVIEW

**Comment by norbertschuler** [comment]
Please add a description what this PR is about and which issues are resolved by this.

**Review by norbertschuler — COMMENTED** [review]
I have not idea yet how to test this as all my test accounts got deleted and I also have no corrupted data available to test.

**Comment by ankitecd** [comment]
To create the project error manually

Replace the following line
https://github.com/Plant-for-the-Planet-org/treemapper/blob/8d6aaf25b51fffb153f67c0098abccc18ffc9438/app/utils/updateSampleTree.ts#L67-L71

with
`        sampleTree = {
          ...sampleTree,
          specieId: null,
          specieName: null,
          specieDiameter: null,
          specieHeight:null,
          status: PENDING_DATA_UPLOAD,
          appMetadata: JSON.stringify(appAdditionalDetails),
        };`
        
First one can make this change this on develop branch and create a registration. Then revert the changes and checkout to this branch to test the PR.

**Comment by norbertschuler** [comment]
> First, one can make this change on develop branch and create a registration. Then revert the changes and checkout to this branch to test the PR.

I followed your description and got a corrupted registration with sample trees missing all the mentioned data. After running this PR and restarting the app with this PR, my erroneous registration was correctly marked, but if I want to edit a sample tree I get an error `Error at /repositories/species/getScientificSpeciesById, [Error: Invalid null value for non-nullable primary key.]`

Simulator Screen Shot - iPhone 13 - 2022-01-16 at 13 18 48Simulator Screen Shot - iPhone 13 - 2022-01-16 at 13 24 11

I was able to edit the polygon though, but on the first try for one sample tree I got a photo only view while for the other I could edit the sample trees and add species, height and diameter. After I closed the editing and opened it again, I finally also could edit and fix my 1st sample tree - I do not know why the display was wrong at first time:

Simulator Screen Shot - iPhone 13 - 2022-01-16 at 13 28 04Simulator Screen Shot - iPhone 13 - 2022-01-16 at 13 28 27

Finally no error was shown any more for my registration and I tried to sync it to the server, but got an error `Error at: /action/upload, changeStatusAndUpload [Error: Some sample tree upload are pending]` while none of the API calls failed. Not sure what this is about, but my registration is shown in "Upload in progress" and I can not do anything anymore about it now as I cannot edit the registration any more:

Simulator Screen Shot - iPhone 13 - 2022-01-16 at 13 37 31

The log shows my registration as following: 
```
 LOG  section [{"additionalDetails": [Array], "appMetadata": "{\"registrationDate\":\"2022-01-16T12:11:23.391Z\",\"deviceLocation\":{\"coordinates\":[9.935538445089009,53.548231740919405],\"type\":\"Point\"},\"appVersion\":\"1.0.7\",\"deviceBrand\":\"Apple\",\"deviceModel\":\"iPhone 13\",\"deviceSystemName\":\"iOS\",\"deviceSystemVersion\":\"15.2\",\"deviceManufacturer\":\"Apple\"}", "completedSampleTreesCount": 5, "donationType": null, "hid": null, "inventory_id": "1642334783162", "lastScreen": "InventoryOverview", "locateTree": "on-site", "locationId": "loc_J2ZsI0AbJgK8uTWbkHT3L6wC", "originalGeometry": null, "plantation_date": 2022-01-16T12:06:23.162Z, "polygons": [Array], "projectId": null, "registrationDate": 2022-01-16T12:29:57.758Z, "sampleTrees": [Array], "sampleTreesCount": 5, "specieDiameter": null, "specieHeight": null, "species": [Array], "status": "PENDING_SAMPLE_TREES_UPLOAD", "tagId": null, "treeType": "multi", "uploadedSampleTreesCount": 0}]
```

**Review by norbertschuler — CHANGES_REQUESTED** [review]
I could not successfully reproduce your test case as in the end I got another stuck registration with `Upload in progress`.

**Review by norbertschuler — APPROVED** [review]
Fixing broken sample trees introduced as described at https://github.com/Plant-for-the-Planet-org/treemapper/pull/553#issuecomment-1009688143 is working now for me. While trying to fix the sample trees, I at first still got problems showing the 1st sample trees only as an image, but after trying for some time I managed to also edit it. Syncing the fix registrations worked fine then. The map UI on iOS still have some problems on my simulator which make the app feel buggy, but that's not the subject of this PR.

**Pull request merged**
