### PR TITLE
Offline maps

### LINKED ISSUE #188: Download Maps
Restrict the user to zoom out if the map area exceeds the threshold of downloadable tile. Also making the download asynchronously in background.

**What are the use cases for this feature?**
This will prevent the user from downloading the map area more than the threshold and later seeing an error. This will also help to do other task while the map is being downloaded in background.

**Feature Checklist**
- [ ] Restrict the user to zoom in and out in between the threshold of the downloadable tile area.
- [ ] Make the download of map asynchronous in background.
- [ ] Address the downloaded size of the map issue in view downloaded map screen.

### PR DESCRIPTION
**Pull request by ankitecd**
(zoom level < 11 can result in more than 6000 tiles)

Fixes #188

### CODE REVIEW

**Comment by norbertschuler** [comment]
I wanted to test this branch, but still got the problem described in https://github.com/Plant-for-the-Planet-org/treemapper/issues/200.

**Comment by norbertschuler** [comment]
We should mark this as ready for review, should we?

**Comment by ankitecd** [comment]
> @ankitecd We should mark this as ready for review, should we?

There are still some pending task which needs to be completed in this pr

**Comment by norbertschuler** [comment]
> > @ankitecd We should mark this as ready for review, should we?
> 
> There are still some pending task which needs to be completed in this pr

I would merge this anyway if no one has time to work on it as it fixes the problem people try to download the map resulting into an error message if the zoom level is not big enough.

**Comment by ankitecd** [comment]
> > > @ankitecd We should mark this as ready for review, should we?
> > 
> > There are still some pending task which needs to be completed in this pr
> 
> I would merge this anyway if no one has time to work on it as it fixes the problem people try to download the map resulting into an error message if the zoom level is not big enough.

Yes I agree. We can merge this

**Review by norbertschuler — APPROVED** [review]

**Pull request merged**
