### PR TITLE
changed metadata format for APi and UI

### LINKED ISSUE #379: Changing value on review screen does not update additional data display
**Describe the bug**
When you change values in the review screen, e.g. diameter or height, the values in the additional data section below do not instantly get updated. But after saving and opening the screen again the data got updated.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Register tree
2. Change diameter or height in review screen
3. See error

**Expected behavior**
Also update additional data section on review screen

**Screenshots**
Screenshot_1623571943Screenshot_1623571970

**Smartphone (please complete the following information):**
- Device: Android emulator
- OS: Android 11
- Tree Mapper App Version: 1.0.2

### PR DESCRIPTION
**Pull request by ankitecd**
Fixes #379 
 Changes in this pull request
-  Fixed Twice confirmation issue while editing page title
- Removed repeating information from app additional details
- Changed app metadata format

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] I defined a dropdown "Droppy" with options "1" and "2", but when I tested it with registering a single tree, the value did not get saved (I loaded my additional data definition from an exported file):

Simulator Screen Shot - iPhone 11 - 2021-06-16 at 12 22 27Simulator Screen Shot - iPhone 11 - 2021-06-16 at 12 23 12Simulator Screen Shot - iPhone 11 - 2021-06-16 at 12 23 17

**Comment by ankitecd** [comment]
> * [ ]  I defined a dropdown "Droppy" with options "1" and "2", but when I tested it with registering a single tree, the value did not get saved (I loaded my additional data definition from an exported file):
> 

This was because while filling the form you might have skipped the dropdown value as it is not required field and it was stored as blank. So I removed storing of blank values in additional details

**Comment by norbertschuler** [comment]
> > * [x]   I defined a dropdown "Droppy" with options "1" and "2", but when I tested it with registering a single tree, the value did not get saved (I loaded my additional data definition from an exported file):
> 
> This was because while filling the form you might have skipped the dropdown value as it is not required field and it was stored as blank. So I removed storing of blank values in additional details

Ok, I tested again twice and was not able to reproduce this error verifying that I always selected a value from the dropdown before continuing the form. So you'r right, I have not selected anything from the dropdown.

**Review by norbertschuler — APPROVED** [review]
LGFM

**Pull request merged**
