### PR TITLE
added bugsnags

### PR DESCRIPTION
**Pull request by tejassonar**
Changes in this pull request:
- Added bugsnags in all over the app

@ankitecd

### CODE REVIEW

**Comment by norbertschuler** [comment]
I have not yet tested. Do we want all these notifications at Bugsnag? If yes, it looks ok for me.

**Comment by norbertschuler** [comment]
In #210 I got the error `Bugsnag could not notify: error must be of type Error` which might indicate that the parameter given to `bugsnag.notify()` somewhere in the code has the wrong type. Can we test this here, once develop is merged into this PR and all the conflicts got solved (maybe just do the changes once more if there are too much conflicts).

**Comment by tejassonar** [comment]
> In #210 I got the error `Bugsnag could not notify: error must be of type Error` which might indicate that the parameter given to `bugsnag.notify()` somewhere in the code has the wrong type. Can we test this here, once develop is merged into this PR and all the conflicts got solved (maybe just do the changes once more if there are too much conflicts).

Sure. I'll merge develop into this PR and will see what's the issue exactly. Also, I'll need to add more `bugsnag.notify()` after merging with develop, if they aren't already added.

**Comment by norbertschuler** [comment]
I am afraid this pull requests is outdated and needs a lot of conflicts to be solved (or done newly?).

**Comment by norbertschuler** [comment]
@tejassonar should we close this?

**Pull request closed without merging**
